services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "wal_level=logical", "-c", "max_replication_slots=4", "-c", "max_wal_senders=4" ]
    volumes:
      - pgdata:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8081:80"

  redpanda:
    image: redpandadata/redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092,OUTSIDE://redpanda:29092
    ports:
      - "9092:9092" # Kafka API
      - "29092:29092" # Internal Kafka API (for other containers)
      - "8082:8082" # Admin API
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  redpanda-console:
    image: redpandadata/console
    depends_on:
      - redpanda
    environment:
      REDPANDA_ADMIN: redpanda:8082
      KAFKA_BROKERS: redpanda:9092
    ports:
      - "8080:8080"

  debezium-connect:
    image: quay.io/debezium/connect
    depends_on:
      - redpanda
      - postgres
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: redpanda:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_config
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_status
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_PLUGIN_PATH: "/kafka/connect,/kafka/plugins"
    volumes:
      - ./plugins:/kafka/plugins

volumes:
  pgdata:
  redpanda-data:
